# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pdokbaggeocoder_form.ui'
#
# Created: Sun May 12 01:07:37 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_pdokbaggeocoder_form(object):
    def setupUi(self, pdokbaggeocoder_form):
        pdokbaggeocoder_form.setObjectName(_fromUtf8("pdokbaggeocoder_form"))
        pdokbaggeocoder_form.setWindowModality(QtCore.Qt.ApplicationModal)
        pdokbaggeocoder_form.setEnabled(True)
        pdokbaggeocoder_form.resize(476, 348)
        pdokbaggeocoder_form.setMouseTracking(False)
        self.buttonBox = QtGui.QDialogButtonBox(pdokbaggeocoder_form)
        self.buttonBox.setGeometry(QtCore.QRect(300, 310, 160, 21))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.browse_shapefile = QtGui.QPushButton(pdokbaggeocoder_form)
        self.browse_shapefile.setGeometry(QtCore.QRect(380, 270, 79, 21))
        self.browse_shapefile.setObjectName(_fromUtf8("browse_shapefile"))
        self.city = QtGui.QComboBox(pdokbaggeocoder_form)
        self.city.setGeometry(QtCore.QRect(300, 202, 161, 27))
        self.city.setObjectName(_fromUtf8("city"))
        self.address = QtGui.QComboBox(pdokbaggeocoder_form)
        self.address.setGeometry(QtCore.QRect(300, 114, 161, 27))
        self.address.setObjectName(_fromUtf8("address"))
        self.address_label = QtGui.QLabel(pdokbaggeocoder_form)
        self.address_label.setGeometry(QtCore.QRect(20, 116, 251, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.address_label.setFont(font)
        self.address_label.setObjectName(_fromUtf8("address_label"))
        self.label_select_file = QtGui.QLabel(pdokbaggeocoder_form)
        self.label_select_file.setGeometry(QtCore.QRect(20, 10, 151, 22))
        self.label_select_file.setObjectName(_fromUtf8("label_select_file"))
        self.infilename = QtGui.QLineEdit(pdokbaggeocoder_form)
        self.infilename.setGeometry(QtCore.QRect(20, 30, 361, 21))
        self.infilename.setText(_fromUtf8(""))
        self.infilename.setReadOnly(False)
        self.infilename.setObjectName(_fromUtf8("infilename"))
        self.browse_infile = QtGui.QPushButton(pdokbaggeocoder_form)
        self.browse_infile.setGeometry(QtCore.QRect(380, 30, 79, 21))
        self.browse_infile.setObjectName(_fromUtf8("browse_infile"))
        self.housenumber = QtGui.QComboBox(pdokbaggeocoder_form)
        self.housenumber.setGeometry(QtCore.QRect(300, 159, 161, 27))
        self.housenumber.setObjectName(_fromUtf8("housenumber"))
        self.housenumber_label = QtGui.QLabel(pdokbaggeocoder_form)
        self.housenumber_label.setGeometry(QtCore.QRect(20, 152, 141, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.housenumber_label.setFont(font)
        self.housenumber_label.setObjectName(_fromUtf8("housenumber_label"))
        self.label_add_column_selection = QtGui.QLabel(pdokbaggeocoder_form)
        self.label_add_column_selection.setGeometry(QtCore.QRect(20, 84, 391, 16))
        self.label_add_column_selection.setObjectName(_fromUtf8("label_add_column_selection"))
        self.radio_column = QtGui.QRadioButton(pdokbaggeocoder_form)
        self.radio_column.setGeometry(QtCore.QRect(20, 209, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_column.setFont(font)
        self.radio_column.setChecked(True)
        self.radio_column.setObjectName(_fromUtf8("radio_column"))
        self.radio_list = QtGui.QRadioButton(pdokbaggeocoder_form)
        self.radio_list.setGeometry(QtCore.QRect(156, 209, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_list.setFont(font)
        self.radio_list.setChecked(False)
        self.radio_list.setAutoExclusive(True)
        self.radio_list.setObjectName(_fromUtf8("radio_list"))
        self.city_label = QtGui.QLabel(pdokbaggeocoder_form)
        self.city_label.setGeometry(QtCore.QRect(20, 192, 91, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.city_label.setFont(font)
        self.city_label.setObjectName(_fromUtf8("city_label"))
        self.line = QtGui.QFrame(pdokbaggeocoder_form)
        self.line.setGeometry(QtCore.QRect(20, 60, 441, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(pdokbaggeocoder_form)
        self.line_2.setGeometry(QtCore.QRect(20, 240, 441, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.address_sublabel = QtGui.QLabel(pdokbaggeocoder_form)
        self.address_sublabel.setGeometry(QtCore.QRect(20, 127, 261, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.address_sublabel.setFont(font)
        self.address_sublabel.setObjectName(_fromUtf8("address_sublabel"))
        self.housenumber_sublabel = QtGui.QLabel(pdokbaggeocoder_form)
        self.housenumber_sublabel.setGeometry(QtCore.QRect(20, 163, 261, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.housenumber_sublabel.setFont(font)
        self.housenumber_sublabel.setObjectName(_fromUtf8("housenumber_sublabel"))
        self.shapefilename = QtGui.QLineEdit(pdokbaggeocoder_form)
        self.shapefilename.setGeometry(QtCore.QRect(20, 270, 361, 21))
        self.shapefilename.setText(_fromUtf8(""))
        self.shapefilename.setReadOnly(False)
        self.shapefilename.setObjectName(_fromUtf8("shapefilename"))
        #self.help_button = QtGui.QToolButton(pdokbaggeocoder_form)
        #self.help_button.setGeometry(QtCore.QRect(20, 310, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        #self.help_button.setFont(font)
        #self.help_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        #self.help_button.setObjectName(_fromUtf8("help_button"))
        self.notfoundfilename = QtGui.QLineEdit(pdokbaggeocoder_form)
        self.notfoundfilename.setEnabled(True)
        self.notfoundfilename.setGeometry(QtCore.QRect(0, 0, 0, 0))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notfoundfilename.sizePolicy().hasHeightForWidth())
        self.notfoundfilename.setSizePolicy(sizePolicy)
        self.notfoundfilename.setMaximumSize(QtCore.QSize(0, 0))
        self.notfoundfilename.setText(_fromUtf8(""))
        self.notfoundfilename.setFrame(True)
        self.notfoundfilename.setReadOnly(False)
        self.notfoundfilename.setObjectName(_fromUtf8("notfoundfilename"))
        self.browse_notfound = QtGui.QPushButton(pdokbaggeocoder_form)
        self.browse_notfound.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.browse_notfound.setObjectName(_fromUtf8("browse_notfound"))

        self.retranslateUi(pdokbaggeocoder_form)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), pdokbaggeocoder_form.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), pdokbaggeocoder_form.reject)
        QtCore.QMetaObject.connectSlotsByName(pdokbaggeocoder_form)

    def retranslateUi(self, pdokbaggeocoder_form):
        pdokbaggeocoder_form.setWindowTitle(QtGui.QApplication.translate("pdokbaggeocoder_form", "PDOK BAG Geocoder", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_shapefile.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Save as...", None, QtGui.QApplication.UnicodeUTF8))
        self.address_label.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Adres (met huisnummer) of Postcode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_select_file.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Selecteer CSV bestand:", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_infile.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.housenumber_label.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Huisnummer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_add_column_selection.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Koppel de kolomvelden uit het CSV bestand: ", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_column.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "selecteer een kolom of", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_list.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "een woonplaats", None, QtGui.QApplication.UnicodeUTF8))
        self.city_label.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Woonplaats", None, QtGui.QApplication.UnicodeUTF8))
        self.address_sublabel.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "huisnummertoevoegingen worden genegeerd", None, QtGui.QApplication.UnicodeUTF8))
        self.housenumber_sublabel.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "optioneel, als huisnummers apart staan", None, QtGui.QApplication.UnicodeUTF8))
        #self.help_button.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Help", None, QtGui.QApplication.UnicodeUTF8))

