# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pdokbaggeocoder_form.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_pdokbaggeocoder_form(object):
    def setupUi(self, pdokbaggeocoder_form):
        pdokbaggeocoder_form.setObjectName(_fromUtf8("pdokbaggeocoder_form"))
        pdokbaggeocoder_form.setWindowModality(QtCore.Qt.ApplicationModal)
        pdokbaggeocoder_form.setEnabled(True)
        pdokbaggeocoder_form.resize(532, 373)
        pdokbaggeocoder_form.setMouseTracking(False)
        self.gridLayout = QtGui.QGridLayout(pdokbaggeocoder_form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.shapefilename = QtGui.QLineEdit(pdokbaggeocoder_form)
        self.shapefilename.setText(_fromUtf8(""))
        self.shapefilename.setReadOnly(False)
        self.shapefilename.setObjectName(_fromUtf8("shapefilename"))
        self.gridLayout.addWidget(self.shapefilename, 13, 0, 1, 3)
        self.housenumber_label = QtGui.QLabel(pdokbaggeocoder_form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.housenumber_label.setFont(font)
        self.housenumber_label.setObjectName(_fromUtf8("housenumber_label"))
        self.gridLayout.addWidget(self.housenumber_label, 7, 0, 1, 1)
        self.housenumber = QtGui.QComboBox(pdokbaggeocoder_form)
        self.housenumber.setObjectName(_fromUtf8("housenumber"))
        self.gridLayout.addWidget(self.housenumber, 8, 2, 1, 2)
        self.browse_infile = QtGui.QPushButton(pdokbaggeocoder_form)
        self.browse_infile.setObjectName(_fromUtf8("browse_infile"))
        self.gridLayout.addWidget(self.browse_infile, 1, 3, 1, 1)
        self.city_label = QtGui.QLabel(pdokbaggeocoder_form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.city_label.setFont(font)
        self.city_label.setObjectName(_fromUtf8("city_label"))
        self.gridLayout.addWidget(self.city_label, 9, 0, 1, 1)
        self.city = QtGui.QComboBox(pdokbaggeocoder_form)
        self.city.setObjectName(_fromUtf8("city"))
        self.gridLayout.addWidget(self.city, 10, 2, 1, 2)
        self.radio_list = QtGui.QRadioButton(pdokbaggeocoder_form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_list.setFont(font)
        self.radio_list.setChecked(False)
        self.radio_list.setAutoExclusive(True)
        self.radio_list.setObjectName(_fromUtf8("radio_list"))
        self.gridLayout.addWidget(self.radio_list, 10, 1, 1, 1)
        self.address = QtGui.QComboBox(pdokbaggeocoder_form)
        self.address.setObjectName(_fromUtf8("address"))
        self.gridLayout.addWidget(self.address, 6, 2, 1, 2)
        self.radio_column = QtGui.QRadioButton(pdokbaggeocoder_form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_column.setFont(font)
        self.radio_column.setChecked(True)
        self.radio_column.setObjectName(_fromUtf8("radio_column"))
        self.gridLayout.addWidget(self.radio_column, 10, 0, 1, 1)
        self.infilename = QtGui.QLineEdit(pdokbaggeocoder_form)
        self.infilename.setText(_fromUtf8(""))
        self.infilename.setReadOnly(False)
        self.infilename.setObjectName(_fromUtf8("infilename"))
        self.gridLayout.addWidget(self.infilename, 1, 0, 1, 3)
        self.line = QtGui.QFrame(pdokbaggeocoder_form)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 2, 0, 1, 4)
        self.address_sublabel = QtGui.QLabel(pdokbaggeocoder_form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.address_sublabel.setFont(font)
        self.address_sublabel.setObjectName(_fromUtf8("address_sublabel"))
        self.gridLayout.addWidget(self.address_sublabel, 6, 0, 1, 2)
        self.address_label = QtGui.QLabel(pdokbaggeocoder_form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.address_label.setFont(font)
        self.address_label.setObjectName(_fromUtf8("address_label"))
        self.gridLayout.addWidget(self.address_label, 5, 0, 1, 2)
        self.label_add_column_selection = QtGui.QLabel(pdokbaggeocoder_form)
        self.label_add_column_selection.setObjectName(_fromUtf8("label_add_column_selection"))
        self.gridLayout.addWidget(self.label_add_column_selection, 3, 0, 2, 3)
        self.browse_shapefile = QtGui.QPushButton(pdokbaggeocoder_form)
        self.browse_shapefile.setObjectName(_fromUtf8("browse_shapefile"))
        self.gridLayout.addWidget(self.browse_shapefile, 13, 3, 1, 1)
        self.housenumber_sublabel = QtGui.QLabel(pdokbaggeocoder_form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.housenumber_sublabel.setFont(font)
        self.housenumber_sublabel.setObjectName(_fromUtf8("housenumber_sublabel"))
        self.gridLayout.addWidget(self.housenumber_sublabel, 8, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(pdokbaggeocoder_form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 14, 2, 1, 2)
        self.label_select_file = QtGui.QLabel(pdokbaggeocoder_form)
        self.label_select_file.setObjectName(_fromUtf8("label_select_file"))
        self.gridLayout.addWidget(self.label_select_file, 0, 0, 1, 1)
        self.line_2 = QtGui.QFrame(pdokbaggeocoder_form)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 12, 0, 1, 4)
        self.notfoundfilename = QtGui.QLineEdit(pdokbaggeocoder_form)
        self.notfoundfilename.setObjectName(_fromUtf8("notfoundfilename"))
        self.gridLayout.addWidget(self.notfoundfilename, 11, 0, 1, 4)

        self.retranslateUi(pdokbaggeocoder_form)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), pdokbaggeocoder_form.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), pdokbaggeocoder_form.reject)
        QtCore.QMetaObject.connectSlotsByName(pdokbaggeocoder_form)

    def retranslateUi(self, pdokbaggeocoder_form):
        pdokbaggeocoder_form.setWindowTitle(_translate("pdokbaggeocoder_form", "PDOK BAG Geocoder", None))
        self.housenumber_label.setText(_translate("pdokbaggeocoder_form", "Huisnummer", None))
        self.browse_infile.setText(_translate("pdokbaggeocoder_form", "Select...", None))
        self.city_label.setText(_translate("pdokbaggeocoder_form", "Woonplaats", None))
        self.radio_list.setText(_translate("pdokbaggeocoder_form", "een woonplaats", None))
        self.radio_column.setText(_translate("pdokbaggeocoder_form", "selecteer een kolom of", None))
        self.address_sublabel.setText(_translate("pdokbaggeocoder_form", "huisnummertoevoegingen worden genegeerd", None))
        self.address_label.setText(_translate("pdokbaggeocoder_form", "Adres (met huisnummer) of Postcode", None))
        self.label_add_column_selection.setText(_translate("pdokbaggeocoder_form", "Koppel de kolomvelden uit het CSV bestand: ", None))
        self.browse_shapefile.setText(_translate("pdokbaggeocoder_form", "Save as...", None))
        self.housenumber_sublabel.setText(_translate("pdokbaggeocoder_form", "optioneel, als huisnummers apart staan", None))
        self.label_select_file.setText(_translate("pdokbaggeocoder_form", "Selecteer CSV bestand:", None))

