# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'baggeocoder__form.ui'
#
# Created: Sat May  4 02:05:38 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_pdokbaggeocoder_form(object):
    def setupUi(self, pdokbaggeocoder_form):
        pdokbaggeocoder_form.setObjectName(_fromUtf8("pdokbaggeocoder_form"))
        pdokbaggeocoder_form.setWindowModality(QtCore.Qt.ApplicationModal)
        pdokbaggeocoder_form.setEnabled(True)
        pdokbaggeocoder_form.resize(440, 450)
        pdokbaggeocoder_form.setMouseTracking(False)
        self.buttonBox = QtGui.QDialogButtonBox(pdokbaggeocoder_form)
        self.buttonBox.setGeometry(QtCore.QRect(260, 410, 160, 21))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.label_save_as = QtGui.QLabel(pdokbaggeocoder_form)
        self.label_save_as.setGeometry(QtCore.QRect(20, 300, 141, 22))
        self.label_save_as.setObjectName(_fromUtf8("label_save_as"))
        self.shapefilename = QtGui.QLineEdit(pdokbaggeocoder_form)
        self.shapefilename.setGeometry(QtCore.QRect(20, 320, 321, 21))
        self.shapefilename.setReadOnly(False)
        self.shapefilename.setObjectName(_fromUtf8("shapefilename"))
        self.browse_shapefile = QtGui.QPushButton(pdokbaggeocoder_form)
        self.browse_shapefile.setGeometry(QtCore.QRect(340, 320, 79, 21))
        self.browse_shapefile.setObjectName(_fromUtf8("browse_shapefile"))
        self.city = QtGui.QComboBox(pdokbaggeocoder_form)
        self.city.setGeometry(QtCore.QRect(260, 138, 161, 27))
        self.city.setObjectName(_fromUtf8("city"))
        self.address = QtGui.QComboBox(pdokbaggeocoder_form)
        self.address.setGeometry(QtCore.QRect(260, 108, 161, 27))
        self.address.setObjectName(_fromUtf8("address"))
        self.address_label = QtGui.QLabel(pdokbaggeocoder_form)
        self.address_label.setGeometry(QtCore.QRect(20, 112, 281, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.address_label.setFont(font)
        self.address_label.setObjectName(_fromUtf8("address_label"))
        self.label_select_file = QtGui.QLabel(pdokbaggeocoder_form)
        self.label_select_file.setGeometry(QtCore.QRect(20, 10, 191, 22))
        self.label_select_file.setObjectName(_fromUtf8("label_select_file"))
        self.infilename = QtGui.QLineEdit(pdokbaggeocoder_form)
        self.infilename.setGeometry(QtCore.QRect(20, 30, 321, 21))
        self.infilename.setText(_fromUtf8(""))
        self.infilename.setReadOnly(False)
        self.infilename.setObjectName(_fromUtf8("infilename"))
        self.browse_infile = QtGui.QPushButton(pdokbaggeocoder_form)
        self.browse_infile.setGeometry(QtCore.QRect(340, 30, 79, 21))
        self.browse_infile.setObjectName(_fromUtf8("browse_infile"))
        self.label_not_found = QtGui.QLabel(pdokbaggeocoder_form)
        self.label_not_found.setGeometry(QtCore.QRect(20, 350, 261, 22))
        self.label_not_found.setObjectName(_fromUtf8("label_not_found"))
        self.notfoundfilename = QtGui.QLineEdit(pdokbaggeocoder_form)
        self.notfoundfilename.setGeometry(QtCore.QRect(20, 370, 321, 21))
        self.notfoundfilename.setReadOnly(False)
        self.notfoundfilename.setObjectName(_fromUtf8("notfoundfilename"))
        self.browse_notfound = QtGui.QPushButton(pdokbaggeocoder_form)
        self.browse_notfound.setGeometry(QtCore.QRect(340, 370, 79, 21))
        self.browse_notfound.setObjectName(_fromUtf8("browse_notfound"))
        self.housenumber = QtGui.QComboBox(pdokbaggeocoder_form)
        self.housenumber.setGeometry(QtCore.QRect(260, 190, 161, 27))
        self.housenumber.setObjectName(_fromUtf8("housenumber"))
        self.housenumber_label = QtGui.QLabel(pdokbaggeocoder_form)
        self.housenumber_label.setGeometry(QtCore.QRect(20, 192, 171, 22))
        self.housenumber_label.setObjectName(_fromUtf8("housenumber_label"))
        self.housenumber_extension_label = QtGui.QLabel(pdokbaggeocoder_form)
        self.housenumber_extension_label.setGeometry(QtCore.QRect(20, 222, 221, 22))
        self.housenumber_extension_label.setObjectName(_fromUtf8("housenumber_extension_label"))
        self.housenumber_extension = QtGui.QComboBox(pdokbaggeocoder_form)
        self.housenumber_extension.setGeometry(QtCore.QRect(260, 220, 161, 27))
        self.housenumber_extension.setObjectName(_fromUtf8("housenumber_extension"))
        self.koppel_kolomvelden_label = QtGui.QLabel(pdokbaggeocoder_form)
        self.koppel_kolomvelden_label.setGeometry(QtCore.QRect(20, 80, 391, 16))
        self.koppel_kolomvelden_label.setObjectName(_fromUtf8("koppel_kolomvelden_label"))
        self.radio_column = QtGui.QRadioButton(pdokbaggeocoder_form)
        self.radio_column.setGeometry(QtCore.QRect(110, 142, 121, 20))
        self.radio_column.setObjectName(_fromUtf8("radio_column"))
        self.radio_list = QtGui.QRadioButton(pdokbaggeocoder_form)
        self.radio_list.setGeometry(QtCore.QRect(110, 165, 101, 20))
        self.radio_list.setChecked(True)
        self.radio_list.setAutoExclusive(True)
        self.radio_list.setObjectName(_fromUtf8("radio_list"))
        self.city_label = QtGui.QLabel(pdokbaggeocoder_form)
        self.city_label.setGeometry(QtCore.QRect(20, 140, 91, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.city_label.setFont(font)
        self.city_label.setObjectName(_fromUtf8("city_label"))
        self.housenumber_letter_label = QtGui.QLabel(pdokbaggeocoder_form)
        self.housenumber_letter_label.setGeometry(QtCore.QRect(20, 252, 171, 22))
        self.housenumber_letter_label.setObjectName(_fromUtf8("housenumber_letter_label"))
        self.housenumber_letter = QtGui.QComboBox(pdokbaggeocoder_form)
        self.housenumber_letter.setGeometry(QtCore.QRect(260, 250, 161, 27))
        self.housenumber_letter.setObjectName(_fromUtf8("housenumber_letter"))
        self.line = QtGui.QFrame(pdokbaggeocoder_form)
        self.line.setGeometry(QtCore.QRect(20, 60, 401, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(pdokbaggeocoder_form)
        self.line_2.setGeometry(QtCore.QRect(20, 286, 401, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))

        self.retranslateUi(pdokbaggeocoder_form)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), pdokbaggeocoder_form.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), pdokbaggeocoder_form.reject)
        QtCore.QMetaObject.connectSlotsByName(pdokbaggeocoder_form)

    def retranslateUi(self, pdokbaggeocoder_form):
        pdokbaggeocoder_form.setWindowTitle(QtGui.QApplication.translate("pdokbaggeocoder_form", "BAG geocoder via de PDOK webservice", None, QtGui.QApplication.UnicodeUTF8))
        self.label_save_as.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Opslaan als Shapefile:", None, QtGui.QApplication.UnicodeUTF8))
        self.shapefilename.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "geocoded.shp", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_shapefile.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Kies...", None, QtGui.QApplication.UnicodeUTF8))
        self.address_label.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Adres (met huisnr) of Postcode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_select_file.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Selecteer een CSV bestand:", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_infile.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Kies...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_not_found.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Niet gevonden locaties CSV bestand:", None, QtGui.QApplication.UnicodeUTF8))
        self.notfoundfilename.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "niet_gevonden.csv", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_notfound.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Kies...", None, QtGui.QApplication.UnicodeUTF8))
        self.housenumber_label.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Huisnummer (1,2,3,...)", None, QtGui.QApplication.UnicodeUTF8))
        self.housenumber_extension_label.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Huisnummer toevoeging (H,1,2..)", None, QtGui.QApplication.UnicodeUTF8))
        self.koppel_kolomvelden_label.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Koppel de kolomvelden voor de zoek query: ", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_column.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "kies kolom", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_list.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "kies uit lijst", None, QtGui.QApplication.UnicodeUTF8))
        self.city_label.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Woonplaats", None, QtGui.QApplication.UnicodeUTF8))
        self.housenumber_letter_label.setText(QtGui.QApplication.translate("pdokbaggeocoder_form", "Huisnummer letter (A-Z)", None, QtGui.QApplication.UnicodeUTF8))

